import type { Plugin } from 'vite'

type EnvMap = Record<string, string | undefined>

interface CspHeaderArtifacts {
  policy: string
  netlifyHeaders: string
  nginxConf: string
}

const SELF = "'self'"
const NONE = "'none'"
const UNSAFE_INLINE = "'unsafe-inline'"

const SPECIAL_SOURCE_VALUES = new Set([
  SELF,
  NONE,
  UNSAFE_INLINE,
  'data:',
  'blob:',
  'http:',
  'https:',
])

function uniqueSorted(values: Iterable<string>): string[] {
  return [...new Set(values)].sort((left, right) => left.localeCompare(right))
}

function splitEnvList(rawValue?: string): string[] {
  if (!rawValue) return []
  return rawValue
    .split(/[\s,]+/)
    .map((item) => item.trim())
    .filter(Boolean)
}

function normalizeOriginSource(rawValue?: string): string | null {
  if (!rawValue) return null

  const trimmed = rawValue.trim()
  if (!trimmed) return null

  if (SPECIAL_SOURCE_VALUES.has(trimmed)) {
    return trimmed
  }

  try {
    const parsed = new URL(trimmed)
    if (parsed.protocol !== 'http:' && parsed.protocol !== 'https:') {
      return null
    }

    return parsed.origin
  } catch {
    return null
  }
}

function collectOrigins(values: string[]): string[] {
  return uniqueSorted(
    values
      .map((value) => normalizeOriginSource(value))
      .filter((value): value is string => Boolean(value)),
  )
}

function resolveBackendConnectSource(env: EnvMap): string | null {
  const fullUrl = normalizeOriginSource(env.VITE_BACKEND_SERVER_URL)
  if (fullUrl) return fullUrl

  const port = env.VITE_BACKEND_SERVER_PORT?.trim()
  if (!port || !/^\d+$/.test(port)) return null

  return `https://*:${port}`
}

function buildDirective(name: string, sources: string[]): string {
  return `${name} ${sources.join(' ')}`
}

export function buildCspReportOnlyPolicy(env: EnvMap): string {
  const connectSrc = uniqueSorted([
    SELF,
    ...collectOrigins([
      env.VITE_OTEL_ENDPOINT ?? '',
      env.VITE_SOURCEMAP_RESOLVER_ENDPOINT ?? '',
      env.VITE_OPENREPLAY_INGEST_POINT ?? '',
      ...splitEnvList(env.VITE_CSP_CONNECT_SRC_EXTRA),
    ]),
    ...(resolveBackendConnectSource(env) ? [resolveBackendConnectSource(env) as string] : []),
  ])

  const frameSrc = uniqueSorted([
    SELF,
    ...collectOrigins(splitEnvList(env.VITE_CSP_FRAME_SRC_EXTRA)),
  ])

  const directives = [
    buildDirective('default-src', [SELF]),
    buildDirective('base-uri', [SELF]),
    buildDirective('form-action', [SELF]),
    buildDirective('frame-ancestors', [SELF]),
    buildDirective('object-src', [NONE]),
    buildDirective('script-src', [SELF]),
    buildDirective('style-src', [SELF, UNSAFE_INLINE]),
    buildDirective('img-src', [SELF, 'data:', 'blob:', 'https:']),
    buildDirective('font-src', [SELF, 'data:']),
    buildDirective('connect-src', connectSrc),
    buildDirective('frame-src', frameSrc),
    buildDirective('worker-src', [SELF, 'blob:']),
    buildDirective('manifest-src', [SELF]),
  ]

  const reportUri = env.VITE_CSP_REPORT_URI?.trim()
  if (reportUri) {
    directives.push(`report-uri ${reportUri}`)
  }

  return directives.join('; ')
}

function escapeForDoubleQuotedHeader(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')
}

export function buildCspHeaderArtifacts(env: EnvMap): CspHeaderArtifacts {
  const policy = buildCspReportOnlyPolicy(env)

  return {
    policy,
    netlifyHeaders: `/*\n  Content-Security-Policy-Report-Only: ${policy}\n`,
    nginxConf:
      '# Generated by vite-plugin/CspHeadersVitePlugin.ts\n' +
      `add_header Content-Security-Policy-Report-Only "${escapeForDoubleQuotedHeader(policy)}" always;\n`,
  }
}

export function cspHeadersPlugin(env: EnvMap): Plugin {
  return {
    name: 'vite-plugin-csp-headers',
    apply: 'build',
    generateBundle() {
      const artifacts = buildCspHeaderArtifacts(env)

      this.emitFile({
        type: 'asset',
        fileName: '_headers',
        source: artifacts.netlifyHeaders,
      })

      this.emitFile({
        type: 'asset',
        fileName: 'security/csp-report-only.conf',
        source: artifacts.nginxConf,
      })
    },
  }
}
