import fs from 'fs'
import path from 'path'
import type { ViteDevServer } from 'vite'

import {
  commonTokens,
  primitiveColorTokens,
  semanticColorTokens,
  spacingScaleTokens,
} from '../src/app/presentation/theme/ThemeToken'

function toKebabCase(str: string): string {
  return str
    .replace(/[/.]/g, '-')
    .replace(/([A-Z])/g, '-$1')
    .replace(/^-/, '')
    .replace(/-+/g, '-')
    .toLowerCase()
}

function appendCssVars(lines: string[], values: Record<string, string>, prefix = ''): void {
  for (const [key, value] of Object.entries(values)) {
    lines.push(`  --${prefix}${toKebabCase(key)}: ${value};`)
  }
}

function generateCss() {
  const lines: string[] = [
    '/*',
    ' * ==========================================================================',
    ' *  THIS FILE IS AUTO-GENERATED BY vite-plugin/ThemeGeneratorVitePlugin.ts',
    ' *  DO NOT EDIT DIRECTLY.',
    ' * ==========================================================================',
    ' */',
    '',
    '@theme {',
  ]

  appendCssVars(lines, commonTokens)
  appendCssVars(lines, spacingScaleTokens)
  appendCssVars(lines, primitiveColorTokens, 'color-primitive-')
  appendCssVars(lines, semanticColorTokens.light)
  lines.push('  --color-primary: var(--color-primary-default);')
  lines.push('  --color-accent: var(--color-accent-default);')
  lines.push('  --color-bg-body: var(--color-background-body);')
  lines.push('  --color-bg-card: var(--color-background-card);')
  lines.push('  --color-border: var(--color-border-default);')

  lines.push('}')
  lines.push('')

  for (const themeKey of Object.keys(semanticColorTokens) as Array<
    keyof typeof semanticColorTokens
  >) {
    if (themeKey === 'light') continue

    lines.push(`[data-theme='${themeKey}'] {`)
    appendCssVars(lines, semanticColorTokens[themeKey])
    lines.push('}')
    lines.push('')
  }

  return `${lines.join('\n')}\n`
}

function writeThemeCss() {
  try {
    const css = generateCss()
    const outputPath = path.resolve(
      process.cwd(),
      'src/app/presentation/theme/styles/generated-theme.css',
    )

    fs.writeFileSync(outputPath, css, 'utf-8')
    console.log(`[ThemeGen] CSS updated at ${new Date().toLocaleTimeString()}`)
  } catch (error) {
    console.error('[ThemeGen] Error:', error)
  }
}

export const themeGeneratorPlugin = () => {
  return {
    name: 'vite-plugin-naive-tailwind-theme',
    buildStart() {
      writeThemeCss()
    },
    handleHotUpdate({ file, server }: { file: string; server: ViteDevServer }) {
      if (file.includes('ThemeToken.ts')) {
        writeThemeCss()
        server.ws.send({
          type: 'full-reload',
          path: '*',
        })
      }
    },
  }
}
