import { resolve } from 'node:path'
import type { ViteDevServer } from 'vite'

import {
  commonTokens,
  primitiveColorTokens,
  semanticColorTokens,
  spacingScaleTokens,
} from '../src/app/presentation/theme/ThemeToken'
import { createGeneratedAsset, writeGeneratedAssetIfChanged } from './shared/generated-asset'

type GenerateThemeCssAssetOptions = {
  sourcePath?: string
  outputPath?: string
  metaPath?: string
  check?: boolean
}

type ThemeGeneratorPluginOptions = Omit<GenerateThemeCssAssetOptions, 'check'>

function toKebabCase(str: string): string {
  return str
    .replace(/[/.]/g, '-')
    .replace(/([A-Z])/g, '-$1')
    .replace(/^-/, '')
    .replace(/-+/g, '-')
    .toLowerCase()
}

function normalizeCssValue(value: string) {
  return value.replace(/#[\da-f]{3,8}\b/gi, (color) => color.toLowerCase())
}

function appendCssVars(lines: string[], values: Record<string, string>, prefix = ''): void {
  for (const [key, value] of Object.entries(values)) {
    const name = `--${prefix}${toKebabCase(key)}`
    const normalizedValue = normalizeCssValue(value)
    const line = `  ${name}: ${normalizedValue};`

    if (line.length > 100 && normalizedValue.includes(',')) {
      lines.push(`  ${name}:`)
      lines.push(`    ${normalizedValue};`)
      continue
    }

    lines.push(line)
  }
}

export function generateThemeCss() {
  const lines: string[] = [
    '/*',
    ' * ==========================================================================',
    ' *  THIS FILE IS AUTO-GENERATED BY vite-plugin/ThemeGeneratorVitePlugin.ts',
    ' *  DO NOT EDIT DIRECTLY.',
    ' * ==========================================================================',
    ' */',
    '',
    '@theme {',
  ]

  appendCssVars(lines, commonTokens)
  appendCssVars(lines, spacingScaleTokens)
  appendCssVars(lines, primitiveColorTokens, 'color-primitive-')
  appendCssVars(lines, semanticColorTokens.light)
  lines.push('  --color-primary: var(--color-primary-default);')
  lines.push('  --color-accent: var(--color-accent-default);')
  lines.push('  --color-bg-body: var(--color-background-body);')
  lines.push('  --color-bg-card: var(--color-background-card);')
  lines.push('  --color-border: var(--color-border-default);')

  lines.push('}')
  lines.push('')

  for (const themeKey of Object.keys(semanticColorTokens) as Array<
    keyof typeof semanticColorTokens
  >) {
    if (themeKey === 'light') continue

    lines.push(`[data-theme='${themeKey}'] {`)
    appendCssVars(lines, semanticColorTokens[themeKey])
    lines.push('}')
    lines.push('')
  }

  return `${lines.join('\n').trimEnd()}\n`
}

function resolveThemeGeneratorOptions(options: GenerateThemeCssAssetOptions = {}) {
  const sourcePath =
    options.sourcePath ?? resolve(process.cwd(), 'src/app/presentation/theme/ThemeToken.ts')
  const outputPath =
    options.outputPath ??
    resolve(process.cwd(), 'src/app/presentation/theme/styles/generated-theme.css')
  const metaPath =
    options.metaPath ??
    resolve(process.cwd(), 'src/app/presentation/theme/styles/generated-theme.meta.json')

  return {
    sourcePath,
    outputPath,
    metaPath,
  }
}

export function generateThemeCssAsset(options: GenerateThemeCssAssetOptions = {}) {
  const paths = resolveThemeGeneratorOptions(options)
  const css = generateThemeCss()

  return writeGeneratedAssetIfChanged(
    createGeneratedAsset({
      name: 'theme-css',
      sourcePaths: [paths.sourcePath],
      outputPath: paths.outputPath,
      metaPath: paths.metaPath,
      content: css,
      hashInput: css,
    }),
    { check: options.check },
  )
}

export const themeGeneratorPlugin = (options: ThemeGeneratorPluginOptions = {}) => {
  const paths = resolveThemeGeneratorOptions(options)
  const generate = () => generateThemeCssAsset(paths)

  return {
    name: 'vite-plugin-naive-tailwind-theme',
    buildStart() {
      generate()
    },
    handleHotUpdate({ file, server }: { file: string; server: ViteDevServer }) {
      if (file !== paths.sourcePath) {
        return
      }

      const result = generate()
      if (result.changed) {
        server.ws.send({
          type: 'full-reload',
          path: '*',
        })
      }
    },
  }
}
