import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

import { commonTokens, colorTokens } from '../src/components/theme/ThemeToken'

// 获取当前文件路径 (ESM 环境下替代 __dirname)
const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

/**
 * 辅助函数：将驼峰命名转换为 kebab-case
 * 例如: radiusSm -> radius-sm, primaryHover -> primary-hover
 */
function toKebabCase(str: string): string {
  return str.replace(/([A-Z])/g, '-$1').toLowerCase()
}

/**
 * 生成 CSS 内容
 */
function generateCss() {
  let cssContent = `/*
 * ==========================================================================
 *  THIS FILE IS AUTO-GENERATED BY scripts/GenerateTheme.ts
 *  DO NOT EDIT DIRECTLY.
 * ==========================================================================
 */

@theme {
  /* ---  通用 CSS 生成 --- */
`

  // 1. 处理 commonTokens (不需要 --color- 前缀)
  // 映射规则: key -> --key-kebab
  for (const [key, value] of Object.entries(commonTokens)) {
    cssContent += `  --${toKebabCase(key)}: ${value};\n`
  }

  cssContent += `
  /* --- 默认主题颜色 (Light Theme Colors) --- */
`

  // 2. 处理 light 主题作为默认值放入 @theme (添加 --color- 前缀)
  // 映射规则: key -> --color-key-kebab
  if (colorTokens.light) {
    for (const [key, value] of Object.entries(colorTokens.light)) {
      cssContent += `  --color-${toKebabCase(key)}: ${value};\n`
    }
  }

  cssContent += `}

/*
 * ==========================================================================
 *  其他主题 (Other Themes)
 * ==========================================================================
 */
`

  // 3. 处理其他主题 (Dark, Sakura...)
  for (const [themeKey, tokens] of Object.entries(colorTokens)) {
    // 跳过 light，因为已经放在 @theme 里作为默认值了
    // 配合 useTheme 逻辑：light 时移除 data-theme 属性，默认读取 @theme
    if (themeKey === 'light') continue

    cssContent += `\n[data-theme='${themeKey}'] {\n`

    for (const [key, value] of Object.entries(tokens)) {
      cssContent += `  --color-${toKebabCase(key)}: ${value};\n`
    }

    cssContent += `}\n`
  }

  return cssContent
}

/**
 * 封装为导出函数
 */
function writeThemeCss() {
  try {
    const css = generateCss()
    // 确保路径相对于项目根目录是正确的
    // 在 Vite 插件中执行时，process.cwd() 通常是项目根目录
    const outputPath = path.resolve(
      process.cwd(),
      'src/components/theme/styles/generated-theme.css',
    )

    fs.writeFileSync(outputPath, css, 'utf-8')
    console.log(`[ThemeGen] CSS updated at ${new Date().toLocaleTimeString()}`)
  } catch (error) {
    console.error('[ThemeGen] Error:', error)
  }
}
export const themeGeneratorPlugin = () => {
  return {
    name: 'vite-plugin-naive-tailwind-theme',
    // Vite 服务启动/构建开始时，先生成一次
    buildStart() {
      writeThemeCss()
    },
    // 热更新处理
    handleHotUpdate({ file, server }) {
      // 监听 ThemeToken.ts 文件的变化
      if (file.includes('ThemeToken.ts')) {
        writeThemeCss()
        // 显式触发 CSS 文件的更新
        // 或者简单地打印日志，让 Tailwind 的监听器去捕获生成的 CSS 变化
        server.ws.send({
          type: 'full-reload',
          path: '*',
        })
      }
    },
  }
}
